/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: All-Wide (https://sketchfab.com/dsm350)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nissan-idx-nismo-258e8dca96404ab8b450c75cd110b5b6
title: Nissan IDX Nismo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_32.geometry} material={materials.Chocofur_Free_Car_02_Glass_01} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[0.42, 0, -0.77]} rotation={[Math.PI / 2, 0.08, 0]} scale={[0.04, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
            <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
            <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
          </group>
          <group position={[0.56, 0.01, -0.78]} rotation={[Math.PI / 2, 0.08, 0]} scale={[0.82, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
          </group>
          <group position={[0.48, 0, -0.77]} rotation={[-3.12, 0, -1.65]} scale={[0.18, 0.22, 0.18]}>
            <mesh geometry={nodes.Object_47.geometry} material={nodes.Object_47.material} />
          </group>
          <group position={[-0.38, -0.01, -0.77]} rotation={[-Math.PI / 2, 0.15, Math.PI]} scale={[0.04, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
            <mesh geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
            <mesh geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
          </group>
          <group position={[-0.52, 0.01, -0.78]} rotation={[-Math.PI / 2, 0.15, -Math.PI]} scale={[0.82, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
          </group>
          <group position={[-0.44, 0, -0.77]} rotation={[3.12, 0, 1.72]} scale={[0.18, 0.22, 0.18]}>
            <mesh geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
          </group>
          <group position={[-0.39, -0.01, 0.74]} rotation={[-Math.PI / 2, 0.06, -Math.PI]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_58.geometry} material={nodes.Object_58.material} />
            <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
            <mesh geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
          </group>
          <group position={[-0.51, 0, 0.74]} rotation={[-Math.PI / 2, 0.06, -Math.PI]} scale={[0.72, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
          </group>
          <group position={[-0.43, 0, 0.75]} rotation={[3.12, 0, 1.63]} scale={[0.18, 0.19, 0.18]}>
            <mesh geometry={nodes.Object_65.geometry} material={nodes.Object_65.material} />
          </group>
          <group position={[0.44, 0, 0.74]} rotation={[Math.PI / 2, 0.06, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_67.geometry} material={nodes.Object_67.material} />
            <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
            <mesh geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
            <mesh geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
          </group>
          <group position={[0.56, 0, 0.74]} rotation={[Math.PI / 2, 0.06, 0]} scale={[0.72, 0.58, 0.58]}>
            <mesh geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
          </group>
          <group position={[0.48, 0, 0.75]} rotation={[-3.12, 0, -1.63]} scale={[0.18, 0.19, 0.18]}>
            <mesh geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_76.geometry} material={materials['Material.003']} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
          </group>
          <group position={[0.18, 0.3, -1.27]} rotation={[1.43, 0, -1.56]} scale={[-0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[0.03, 0.01, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.6, 0.6, 0.6]}>
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
